"""Destructive Command Guard (DCG) wrapper.

Provides a simple rule-based gate to catch and block destructive shell/OS
commands generated by agents. This is intentionally conservative — the
real project should replace heuristics with a policy engine or human-in-the-loop.
"""
import re
from typing import Dict
from src.socket_instance import emit_agent


class DCG:
    def __init__(self):
        self.destructive_patterns = [
            r"\brm\s+-rf\b",
            r"\brm\s+-r\b",
            r"\bshutdown\b",
            r"\bpoweroff\b",
            r"\b:>\b",
            r"\bdd\s+if=\b",
            r"\bmkfs\b",
        ]

    def check_command(self, command: str) -> Dict[str, str]:
        """Return a dict with `allowed` 'yes'/'no' and `reason`."""
        cmd = command.strip()
        for pat in self.destructive_patterns:
            if re.search(pat, cmd, re.IGNORECASE):
                emit_agent("info", {"type": "warning", "message": "DCG blocked a destructive command"})
                return {"allowed": "no", "reason": "destructive command detected"}

        # safe by default
        return {"allowed": "yes", "reason": "ok"}


dcg = DCG()
